- hosts: localhost
  tasks:
  - name: "Launching the Master over AWS  ec2 instance"
    ec2:
      key_name: 2021_key
      instance_type: t2.micro
      image: ami-08e0ca9924195beba
      count: 1
      assign_public_ip: yes
      region: ap-south-1
      vpc_subnet_id: subnet-a96175c1
      instance_tags: {"Name":"Master", "Clusture":"K8s Clusture"}

- hosts: localhost
  tasks:
  - name: "Launching the Worker Node over AWS  ec2 instance"
    ec2:
      key_name: 2021_key
      instance_type: t2.micro
      image: ami-08e0ca9924195beba
      count: 2
      assign_public_ip: yes
      region: ap-south-1
      vpc_subnet_id: subnet-a96175c1
      instance_tags: {"Name":"Worker", "Clusture":"K8s Clusture"}

